import{a as y,S as g,i as h}from"./assets/vendor-95dc692e.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();async function b(){const t=new URLSearchParams({key:"42957626-41f27679caf00334274850a6e",q:c,image_type:"photo",orientation:"horizontal",safesearch:"true",page:a,per_page:p}),n=await y.get(`https://pixabay.com/api/?${t}`);return S(),n.data}function w(t){const i=t.hits.map(o=>`<li class="gallery-item">
              <a class="gallery-link" href="${o.largeImageURL}">
                <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
              </a>
              <div class="stats">
                <p class="text">Likes<br/>${o.likes}</p>
                <p class="text">Views<br/>${o.views}</p>
                <p class="text">Comments<br/>${o.comments}</p>
                <p class="text">Downloads<br/>${o.downloads}</p>
              </div>
            </li>`).join("");s.gallery.insertAdjacentHTML("beforeend",i),L.refresh()}let a=1,p=15;const s={gallery:document.querySelector(".gallery"),form:document.querySelector(".form"),wordInput:document.querySelector(".input"),loader:document.querySelector(".loader"),button:document.querySelector(".btn-load")},L=new g(".gallery-link",{captionsData:"alt",captionDelay:250,overlay:!0,overlayOpacity:.7});let c="";d();f();s.form.addEventListener("submit",v);s.button.addEventListener("click",m);function v(t){t.preventDefault(),a=1,s.gallery.innerHTML="",c=s.wordInput.value.trim(),f(),c!==""?m():u("Please complete the field!"),s.form.reset()}async function m(){const t=await b(),n=Math.ceil(t.totalHits/p);if(a+=1,t.hits.length===0)u("Sorry, there are no images matching your search query. Please try again!");else if(a>=n)u("We're sorry, but you've reached the end of search results."),f(),d();else try{w(t),d(),a>1&&q()}catch(e){console.log(e)}const o=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o.height*2,behavior:"smooth"}),s.form.reset()}function u(t){h.error({title:"Error",message:t,position:"topRight"})}function S(){s.loader.style.display="block"}function d(){s.loader.style.display="none"}function q(){s.button.style.display="block"}function f(){s.button.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
