import{a as m,S as g,i as h}from"./assets/vendor-95dc692e.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();async function d(){const t=new URLSearchParams({key:"42957626-41f27679caf00334274850a6e",q:l,image_type:"photo",orientation:"horizontal",safesearch:"true",page:i,per_page:f}),a=await m.get(`https://pixabay.com/api/?${t}`);return v(),a.data}function b(t){if(t.hits.length===0)u("Sorry, there are no images matching your search query. Please try again!");else{const n=t.hits.map(r=>`<li class="gallery-item">
                <a class="gallery-link" href="${r.largeImageURL}">
                  <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
                </a>
                <div class="stats">
                  <p class="text">Likes<br/>${r.likes}</p>
                  <p class="text">Views<br/>${r.views}</p>
                  <p class="text">Comments<br/>${r.comments}</p>
                  <p class="text">Downloads<br/>${r.downloads}</p>
                </div>
              </li>`).join("");s.gallery.insertAdjacentHTML("beforeend",n),w.refresh()}}let i=1,f=15;const s={gallery:document.querySelector(".gallery"),form:document.querySelector(".form"),wordInput:document.querySelector(".input"),loader:document.querySelector(".loader"),button:document.querySelector(".btn-load")},w=new g(".gallery-link",{captionsData:"alt",captionDelay:250,overlay:!0,overlayOpacity:.7});let l="";y();P();s.form.addEventListener("submit",L);s.button.addEventListener("click",p);function L(t){t.preventDefault(),s.gallery.innerHTML="",l=s.wordInput.value.trim(),l!==""?p():u("Please complete the field!")}async function p(){const t=await d(),a=Math.ceil(t.totalHits/f);if(i>=a)u("We're sorry, but you've reached the end of search results.");else try{const n=await d(l);b(n),y(),i+=1,i>1&&S()}catch(n){console.log(n)}s.form.reset()}function u(t){h.error({title:"Error",message:t,position:"topRight"})}function v(){s.loader.style.display="block"}function y(){s.loader.style.display="none"}function S(){s.button.style.display="block"}function P(){s.button.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
