import{a as g,S as h,i as b}from"./assets/vendor-95dc692e.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&t(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();async function p(){const o=new URLSearchParams({key:"42957626-41f27679caf00334274850a6e",q:c,image_type:"photo",orientation:"horizontal",safesearch:"true",page:n,per_page:m}),a=await g.get(`https://pixabay.com/api/?${o}`);return S(),a.data}function w(o){const i=o.hits.map(t=>`<li class="gallery-item">
              <a class="gallery-link" href="${t.largeImageURL}">
                <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}" />
              </a>
              <div class="stats">
                <p class="text">Likes<br/>${t.likes}</p>
                <p class="text">Views<br/>${t.views}</p>
                <p class="text">Comments<br/>${t.comments}</p>
                <p class="text">Downloads<br/>${t.downloads}</p>
              </div>
            </li>`).join("");s.gallery.insertAdjacentHTML("beforeend",i),L.refresh()}let n=1,m=15;const s={gallery:document.querySelector(".gallery"),form:document.querySelector(".form"),wordInput:document.querySelector(".input"),loader:document.querySelector(".loader"),button:document.querySelector(".btn-load")},L=new h(".gallery-link",{captionsData:"alt",captionDelay:250,overlay:!0,overlayOpacity:.7});let c="";d();f();s.form.addEventListener("submit",v);s.button.addEventListener("click",y);function v(o){o.preventDefault(),n=1,s.gallery.innerHTML="",c=s.wordInput.value.trim(),f(),c!==""?y():u("Please complete the field!"),s.form.reset()}async function y(){const o=await p(),a=Math.ceil(o.totalHits/m);if(n+=1,o.hits.length===0)u("Sorry, there are no images matching your search query. Please try again!");else if(n>=a)u("We're sorry, but you've reached the end of search results."),f(),d();else try{const e=await p();w(e),d(),n>1&&q()}catch(e){console.log(e)}const t=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t.height*2,behavior:"smooth"}),s.form.reset()}function u(o){b.error({title:"Error",message:o,position:"topRight"})}function S(){s.loader.style.display="block"}function d(){s.loader.style.display="none"}function q(){s.button.style.display="block"}function f(){s.button.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
